---
kind: pipeline
type: docker
name: Build & Release

steps:
  - name: Build
    image: dlangchina/dlang-dmd
    commands:
      - dub build -b release
      - strip ./lumarsh
  - name: Release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_API_KEY
      files: ./lumarsh
    when:
      event: tag